# Backend Railway Configuration
# This file configures the backend service deployment

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

# Only rebuild backend when backend files change
watchPatterns = ["backend/**"]

[deploy]
startCommand = "node dist/index.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Production environment configuration
[environments.production]
[environments.production.deploy]
# Backend starts with environment variables from Railway dashboard
