// AUTO-GENERATED by scripts/write-build-info.mjs
// Do not edit manually. Regenerated on each build.
export const BUILD_TIME = '2025-10-26T22:08:56.280Z' as const
export const GIT_SHA = 'de2430e' as const
export const GIT_SHA_FULL = 'de2430e93a527feff757089149da7b315db1c603' as const
export const GIT_BRANCH = 'main' as const
export const VERCEL_URL = '' as const
export const VERCEL_ENV = '' as const
