// AUTO-GENERATED by scripts/write-build-info.mjs
// Do not edit manually. Regenerated on each build.
export const BUILD_TIME = '2025-10-27T01:13:31.419Z' as const
export const GIT_SHA = 'e7d01b2' as const
export const GIT_SHA_FULL = 'e7d01b2bf5c370fec690f788bcb89c3474420d81' as const
export const GIT_BRANCH = 'main' as const
export const VERCEL_URL = '' as const
export const VERCEL_ENV = '' as const
