// AUTO-GENERATED by scripts/write-build-info.mjs
// Do not edit manually. Regenerated on each build.
export const BUILD_TIME = '2025-10-27T14:50:14.064Z' as const
export const GIT_SHA = 'bc08bb7' as const
export const GIT_SHA_FULL = 'bc08bb724f90ba7fffff13eb3eed79f8dff4b861' as const
export const GIT_BRANCH = 'recovery/vercel-guard' as const
export const VERCEL_URL = '' as const
export const VERCEL_ENV = '' as const
