name: CI - Type Check

on:
  push:
    branches:
      - main
      # Add more protected branches as needed, e.g.:
      # - release/*
      # - ci/*
  pull_request:
    branches: ["**"]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            backend/package-lock.json
            frontend/package-lock.json

      - name: Install backend dependencies
        working-directory: backend
        run: npm install --no-audit --no-fund

      - name: Backend type check
        working-directory: backend
        run: |
          npm run -s build:types || npx tsc -p tsconfig.json --noEmit

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install --no-audit --no-fund

      - name: Frontend type check
        working-directory: frontend
        run: npm run type-check
