name: CI

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install root deps
        run: npm ci

      - name: Install backend deps
        working-directory: backend
        run: npm ci

      - name: Install frontend deps
        working-directory: frontend
        run: npm ci

      - name: Typecheck frontend
        working-directory: frontend
        run: npm run -s type-check

      - name: Build frontend
        working-directory: frontend
        run: npm run -s build

      - name: Lint frontend
        working-directory: frontend
        continue-on-error: true
        run: |
          npx eslint . --ext .ts,.tsx
          npx prettier --check "src/**/*.{ts,tsx,json,css}"

      - name: Lint backend
        working-directory: backend
        continue-on-error: true
        run: |
          npx eslint . --ext .ts
          npx prettier --check "**/*.{ts,js,json,md,yml,yaml}"

      - name: Unit tests - frontend
        working-directory: frontend
        run: npx vitest run --silent

      - name: Unit tests - backend
        working-directory: backend
        env:
          # Provide a dummy OpenAI key to satisfy env schema; backend tests should not call network
          OPENAI_API_KEY: "test-test-test-test"
        run: npx vitest run --silent

      - name: E2E - Playwright install
        run: npx playwright install --with-deps chromium

      - name: E2E - Run tests
        env:
          OPENAI_API_KEY: "test-test-test-test"
        run: npx playwright test --reporter=list

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: ignore

      - name: Upload e2e JSON results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-results
          path: e2e-results.json
          if-no-files-found: ignore
