name: Frontend CI

on:
    push:
        paths:
            - "frontend/**"
            - ".github/workflows/frontend-ci.yml"
    pull_request:
        paths:
            - "frontend/**"
            - ".github/workflows/frontend-ci.yml"

permissions:
    contents: read

jobs:
    build-test:
        name: Type-check, Test, Build
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: frontend
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"
                  cache-dependency-path: frontend/package-lock.json

            - name: Install dependencies
              run: npm ci || npm i --no-audit --no-fund

            - name: Type-check
              run: npm run -s type-check

            - name: Unit tests
              run: npm test --silent

            - name: Build
              run: npm run -s build

            - name: Generate render metrics baseline
              run: npm run -s perf:baseline

            - name: Upload baseline artifact
              uses: actions/upload-artifact@v4
              with:
                  name: render-metrics-baseline
                  path: |
                      docs/perf/metrics-baseline.md
                      docs/perf/metrics-baseline.json
